services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: "2181:2181"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - zookeeper_data:/bitnami

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT://localhost:29092 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT 
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami
volumes:
  zookeeper_data:
  kafka_data:
    